branches:
  except:
  - donttestme
language: bash
sudo: required
services:
- docker
install:
- travis_wait make build-no-cache
script:
- make generate-accounts run fixtures tests
after_script:
- make clean
env:
- ENABLE_CLAMAV=1 ENABLE_SPAMASSASSIN=1 ENABLE_FAIL2BAN=1 ONE_DIR=1 ENABLE_POP3=1 SA_TAG=1.0 SA_TAG2=2.0 SA_KILL=3.0 VIRUSMAILS_DELETE_DELAY=7 ENABLE_MANAGESIEVE=1 ENABLE_FETCHMAIL= 1 PERMIT_DOCKER=host    DMS_DEBUG=0 SASL_PASSWD="external domain.com username:password"
- ENABLE_CLAMAV=0 ENABLE_SPAMASSASSIN=0 ENABLE_FAIL2BAN=0 ONE_DIR=0 ENABLE_POP3=0 SA_TAG=    SA_TAG2=    SA_KILL=    VIRUSMAILS_DELETE_DELAY=  ENABLE_MANAGESIEVE=0 ENABLE_FETCHMAIL= 0 PERMIT_DOCKER=network DMS_DEBUG=0

notifications:
  slack:
    secure: TTo1z9nbZCWcIdfPwypubNa3y+pwvfgDGlzEVAGEuK7uuIpmEoAcAUNSSPTnbewDGHnDl8t/ml93MtvP+a+IVuAKytMqF39PHyoZO7aUl9J62V+G75OmnyGjXGJm40pQosCS6LzqoRRYXotl9+fwH568Kf4ifXCrMZX1d+ir7Ww=
