branches:
  except:
  - donttestme
language: bash
sudo: required
services:
- docker
install:
- travis_retry travis_wait make build-no-cache
script:
- make generate-accounts run generate-accounts-after-run fixtures tests
after_script:
- make clean
notifications:
  slack:
    secure: TTo1z9nbZCWcIdfPwypubNa3y+pwvfgDGlzEVAGEuK7uuIpmEoAcAUNSSPTnbewDGHnDl8t/ml93MtvP+a+IVuAKytMqF39PHyoZO7aUl9J62V+G75OmnyGjXGJm40pQosCS6LzqoRRYXotl9+fwH568Kf4ifXCrMZX1d+ir7Ww=
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7ec65291bfb4bf1f8518
    on_success: always
    on_failure: always
    on_start: never
