language: C
sudo: false
before_install:
  - wget https://kubernetes-helm.storage.googleapis.com/helm-v2.7.2-linux-amd64.tar.gz
  - tar xzvf helm-v2.7.2-linux-amd64.tar.gz
  - mv linux-amd64/helm helm
  - chmod u+x helm
  - wget https://github.com/garethr/kubeval/releases/download/0.7.0/kubeval-linux-amd64.tar.gz 
  - tar xzvf kubeval-linux-amd64.tar.gz
  - chmod u+x kubeval
  - wget https://github.com/garethr/kubetest/releases/download/0.1.0/kubetest-linux-amd64.tar.gz 
  - tar xzvf kubetest-linux-amd64.tar.gz
  - chmod u+x kubetest
script:
  - ./helm template helm-chart/docker-mailserver | ./kubeval -v $KUBERNETES_VERSION
env:
  - KUBERNETES_VERSION="1.14.0"
jobs:
  include:
    - stage: kubetest
      script:
        - ./helm template helm-chart/docker-mailserver | ./kubetest --verbose
    - stage: unittest
      script:
        - ./helm unittest helm-chart/docker-mailserver 
