suite: test ingress that should fail
templates:
  - ingress.yaml
tests:
  - it: should fail render nothing if not enabled
    asserts:
      - hasDocuments:
          count: 1

  - it: should fail render ingress right if enabled
    set:
      ingress.enabled: true
      service.externalPort: 12345
    release:
      name: my-release
    asserts:
      - contains:
          path: spec.rules[0].http.paths
          content:
            path: /
            backend:
              serviceName: my-release-basic
              servicePort: 54321
      - isNotNull:
          path: spec.tls

  - it: should fail set annotations if given
    set:
      ingress.enabled: true
      ingress.annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        ingress.kubernetes.io/rewrite-target: /
    release:
      name: my-release
    asserts:
      - isEmpty:
          path: metadata.annotations

  - it: should fail set tls if given
    set:
      ingress.enabled: true

    release:
      name: my-release
    asserts:
      - equal:
          path: spec.tls
          value:
            - secretName: my-tls-secret
