name: Update contributors
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 1 * *'

jobs:
  delete-old-branch:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - name: Delete old contributors-update branch
        uses: dawidd6/action-delete-branch@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          branches: contributors-update

  add-contributors:
    runs-on: ubuntu-latest
    needs: delete-old-branch
    steps:
      - uses: actions/checkout@v3

      - name: Create contributors-update branch
        uses: peterjgrainger/action-create-branch@v2.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branch: 'contributors-update'

      - name: Auto-add contributors
        uses: BobAnkh/add-contributors@v0.2.2
        with:
          BRANCH: 'contributors-update'
          PULL_REQUEST: 'master'
          CONTRIBUTOR: '## Contributors'
          COLUMN_PER_ROW: '6'
          ACCESS_TOKEN: ${{secrets.GITHUB_TOKEN}}
          IMG_WIDTH: '100'
          FONT_SIZE: '14'
          PATH: '/CONTRIBUTORS.md'
          COMMIT_MESSAGE: 'docs(CONTRIBUTORS): update contributors'
          AVATAR_SHAPE: 'round'

      # This workflow will not trigger a `pull_request` event without a PAT.
      # The lint workflow is not important for this type of PR, skip it and pretend it was successful:
      - name: 'Get the latest commit hash from the contributors-update branch'
        id: commit-data
        run: |
          git pull
          git checkout contributors-update
          echo "::set-output name=head_sha::$(git rev-parse contributors-update)"

      - name: 'Commit Status: Set Lint status to success (skipped)'
        uses: myrotvorets/set-commit-status-action@1.1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # Skipped workflows are still assigned a "success" status:
          status: success
          # This should be the correct commit SHA on the contributors-update branch:
          sha: ${{ steps.commit-data.outputs.head_sha }}
          # Name of status check to add/update:
          context: 'lint'
          # Optional message/note we can inline to the right of the context name in the UI:
          description: "Lint skipped. Not relevant."
