name: "Lint"

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches:
      - master

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive
      - name: Hadolint
        run: |
          sudo curl -S -L https://github.com/hadolint/hadolint/releases/download/v${HADOLINT_VERSION}/hadolint-$(uname -s)-$(uname -m) -o /usr/local/bin/hadolint
          sudo chmod +rx /usr/local/bin/hadolint
          make hadolint
        env:
          HADOLINT_VERSION: 2.4.1
      - name: ShellCheck
        run: |
          sudo curl -S -L "https://github.com/koalaman/shellcheck/releases/download/v${SHELLCHECK_VERSION}/shellcheck-v${SHELLCHECK_VERSION}.linux.x86_64.tar.xz" | tar -xJ
          sudo mv "shellcheck-v${SHELLCHECK_VERSION}/shellcheck" /usr/bin/
          sudo rm -rf "shellcheck-v${SHELLCHECK_VERSION}"
          make shellcheck
        env:
          SHELLCHECK_VERSION: 0.7.2
      - name: ECLint
        run: |
          sudo curl -S -L "https://github.com/editorconfig-checker/editorconfig-checker/releases/download/${ECLINT_VERSION}/ec-linux-amd64.tar.gz" | tar -xaz
          sudo mv bin/ec-linux-amd64 /usr/bin/eclint
          sudo rm -rf bin
          sudo chmod +x /usr/bin/eclint
          make eclint
        env:
          ECLINT_VERSION: 2.3.5
